- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "hello yuvasai"
    ansible.builtin.debug:
      msg: " {{ greeating | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "hellow yuvasai"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"      