- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "hello yuvasai"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "hellow yuvasai"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"      

  - name: get the unique values
    vars:
      numbers: [1,3,5,7,9,10,7,5,3,1]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"      

  - name: get the min and max
    vars:
       numbers: [1,3,5,7,9,10,7,5,3,1]
    ansible.builtin.debug:
      msg: " min: {{ numbers | min }}, max: {{ numbers | max }}"      

  - name:
    vars:
      COURSE:
        name: "devops with aws"
        duration: "120"
        trainner: "shivakumar"
    ansible.builtin.debug:
     msg: "{{ COURSE | dict2items }}"   

  - name: check ip address
    vars:
      myip: "356.168.1.1"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"       
